// AUTO-GENERATED by scripts/generate-catalog.cjs — do not hand-edit
// Source: AVIATOR_BIBLE.xlsx

export interface AmpChannel {
  id: string
  label: string
  outputMode: 'lo-z' | 'hi-z'
  maxWatts?: number        // W at ratedImpedance
  ratedImpedance?: number  // Ω
  minImpedance?: number    // Ω
  hiZWatts?: number        // 70V channel capacity (W)
  // BTL (bridge-tied load) fields — master channel only
  btlWatts?: number           // W in BTL mode
  btlRatedImpedance?: number  // Ω rated in BTL mode
  btlMinImpedance?: number    // Ω minimum load in BTL mode
  btlPairId?: string          // ID of slave channel bridged with this master
}

export interface AmpModel {
  modelId: string
  name: string
  series: string
  subtitle: string
  dealer?: number
  msrp?: number
  channels: AmpChannel[]
  /** True for sub-amplifiers — shown in the Subwoofers sidebar section, not Amplifiers */
  subOnly?: boolean
}

export interface SpeakerModel {
  modelId: string
  name: string
  collection: string
  brand?: string
  speakerType: 'lo-z' | 'hi-z' | 'tappable'
  impedance?: number        // Ω nominal
  tapOptions?: number[]     // 70V watt taps (descending)
  specsUnavailable?: boolean
  sensitivity?: number      // dB SPL @ 1W/1m (for SPL estimation)
  maxWatts?: number         // Continuous power handling (W)
  coverageAngle?: number    // Nominal dispersion angle (degrees, for future coverage calc)
  dealer?: number           // US dealer cost ($)
  msrp?: number             // MSRP ($)
}

export interface SourceModel {
  modelId: string
  name: string
  badge: string
  description: string
}

export const AMPS: AmpModel[] = [
  {
    "modelId": "DSP2-200",
    "name": "DSP2-200",
    "series": "Foundation",
    "subtitle": "2× Lo-Z",
    "dealer": 511,
    "msrp": 1075,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 200,
        "ratedImpedance": 4,
        "minImpedance": 4
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 200,
        "ratedImpedance": 4,
        "minImpedance": 4
      }
    ]
  },
  {
    "modelId": "DSP3-150",
    "name": "DSP3-150",
    "series": "Foundation",
    "subtitle": "3× Lo-Z",
    "dealer": 753,
    "msrp": 1516,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch L Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 150,
        "ratedImpedance": 4,
        "minImpedance": 4
      },
      {
        "id": "loz2",
        "label": "Ch R Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 150,
        "ratedImpedance": 4,
        "minImpedance": 4
      },
      {
        "id": "loz3",
        "label": "Sub Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 300,
        "ratedImpedance": 4,
        "minImpedance": 4
      }
    ]
  },
  {
    "modelId": "DSP60.8",
    "name": "DSP60.8",
    "series": "Foundation",
    "subtitle": "8× Lo-Z · 4× Hi-Z",
    "dealer": 1183,
    "msrp": 1984,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 4,
        "minImpedance": 4,
        "btlPairId": "loz2",
        "hiZWatts": 125
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 4,
        "minImpedance": 4
      },
      {
        "id": "loz3",
        "label": "Ch 3 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 4,
        "minImpedance": 4,
        "btlPairId": "loz4",
        "hiZWatts": 125
      },
      {
        "id": "loz4",
        "label": "Ch 4 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 4,
        "minImpedance": 4
      },
      {
        "id": "loz5",
        "label": "Ch 5 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 4,
        "minImpedance": 4,
        "btlPairId": "loz6",
        "hiZWatts": 125
      },
      {
        "id": "loz6",
        "label": "Ch 6 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 4,
        "minImpedance": 4
      },
      {
        "id": "loz7",
        "label": "Ch 7 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 4,
        "minImpedance": 4,
        "btlPairId": "loz8",
        "hiZWatts": 125
      },
      {
        "id": "loz8",
        "label": "Ch 8 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 4,
        "minImpedance": 4
      }
    ]
  },
  {
    "modelId": "SubA150",
    "name": "SubA150",
    "series": "Foundation",
    "subtitle": "1× Lo-Z",
    "subOnly": true,
    "dealer": 420,
    "msrp": 903,
    "channels": [
      {
        "id": "loz1",
        "label": "Sub Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 80,
        "ratedImpedance": 8,
        "minImpedance": 2
      }
    ]
  },
  {
    "modelId": "SubA500",
    "name": "SubA500",
    "series": "Foundation",
    "subtitle": "1× Lo-Z",
    "subOnly": true,
    "dealer": 807,
    "msrp": 1742,
    "channels": [
      {
        "id": "loz1",
        "label": "Sub Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2
      }
    ]
  },
  {
    "modelId": "ProA1000.1",
    "name": "ProA1000.1",
    "series": "Pro",
    "subtitle": "2× Lo-Z · 1× Hi-Z",
    "dealer": 1258,
    "msrp": 2097,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz2",
        "hiZWatts": 1000
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2
      }
    ]
  },
  {
    "modelId": "ProA1000.2",
    "name": "ProA1000.2",
    "series": "Pro",
    "subtitle": "4× Lo-Z · 2× Hi-Z",
    "dealer": 1774,
    "msrp": 2957,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz2",
        "hiZWatts": 1000
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2
      },
      {
        "id": "loz3",
        "label": "Ch 3 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz4",
        "hiZWatts": 1000
      },
      {
        "id": "loz4",
        "label": "Ch 4 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2
      }
    ]
  },
  {
    "modelId": "ProA1000.4",
    "name": "ProA1000.4",
    "series": "Pro",
    "subtitle": "8× Lo-Z · 4× Hi-Z",
    "dealer": 3000,
    "msrp": 4999,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz2",
        "hiZWatts": 1000
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2
      },
      {
        "id": "loz3",
        "label": "Ch 3 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz4",
        "hiZWatts": 1000
      },
      {
        "id": "loz4",
        "label": "Ch 4 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2
      },
      {
        "id": "loz5",
        "label": "Ch 5 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz6",
        "hiZWatts": 1000
      },
      {
        "id": "loz6",
        "label": "Ch 6 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2
      },
      {
        "id": "loz7",
        "label": "Ch 7 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz8",
        "hiZWatts": 1000
      },
      {
        "id": "loz8",
        "label": "Ch 8 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 250,
        "ratedImpedance": 8,
        "minImpedance": 2
      }
    ]
  },
  {
    "modelId": "ProA1200.1",
    "name": "ProA1200.1",
    "series": "Pro",
    "subtitle": "2× Lo-Z · 1× Hi-Z",
    "dealer": 1387,
    "msrp": 2312,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz2",
        "hiZWatts": 1200
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2
      }
    ]
  },
  {
    "modelId": "ProA1200.2",
    "name": "ProA1200.2",
    "series": "Pro",
    "subtitle": "4× Lo-Z · 2× Hi-Z",
    "dealer": 1968,
    "msrp": 3279,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz2",
        "hiZWatts": 1200
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2
      },
      {
        "id": "loz3",
        "label": "Ch 3 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz4",
        "hiZWatts": 1200
      },
      {
        "id": "loz4",
        "label": "Ch 4 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2
      }
    ]
  },
  {
    "modelId": "ProA1200.4",
    "name": "ProA1200.4",
    "series": "Pro",
    "subtitle": "8× Lo-Z · 4× Hi-Z",
    "dealer": 3354,
    "msrp": 5590,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz2",
        "hiZWatts": 1200
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2
      },
      {
        "id": "loz3",
        "label": "Ch 3 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz4",
        "hiZWatts": 1200
      },
      {
        "id": "loz4",
        "label": "Ch 4 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2
      },
      {
        "id": "loz5",
        "label": "Ch 5 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz6",
        "hiZWatts": 1200
      },
      {
        "id": "loz6",
        "label": "Ch 6 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2
      },
      {
        "id": "loz7",
        "label": "Ch 7 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2,
        "btlPairId": "loz8",
        "hiZWatts": 1200
      },
      {
        "id": "loz8",
        "label": "Ch 8 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 400,
        "ratedImpedance": 8,
        "minImpedance": 2
      }
    ]
  },
  {
    "modelId": "ProA125.1",
    "name": "ProA125.1",
    "series": "Pro",
    "subtitle": "2× Lo-Z · 1× Hi-Z",
    "dealer": 549,
    "msrp": 914,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz2",
        "hiZWatts": 125
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4
      }
    ]
  },
  {
    "modelId": "ProA125.2",
    "name": "ProA125.2",
    "series": "Pro",
    "subtitle": "4× Lo-Z · 2× Hi-Z",
    "dealer": 774,
    "msrp": 1290,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz2",
        "hiZWatts": 125
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4
      },
      {
        "id": "loz3",
        "label": "Ch 3 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz4",
        "hiZWatts": 125
      },
      {
        "id": "loz4",
        "label": "Ch 4 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4
      }
    ]
  },
  {
    "modelId": "ProA125.4",
    "name": "ProA125.4",
    "series": "Pro",
    "subtitle": "8× Lo-Z · 4× Hi-Z",
    "dealer": 1323,
    "msrp": 2204,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz2",
        "hiZWatts": 125
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4
      },
      {
        "id": "loz3",
        "label": "Ch 3 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz4",
        "hiZWatts": 125
      },
      {
        "id": "loz4",
        "label": "Ch 4 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4
      },
      {
        "id": "loz5",
        "label": "Ch 5 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz6",
        "hiZWatts": 125
      },
      {
        "id": "loz6",
        "label": "Ch 6 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4
      },
      {
        "id": "loz7",
        "label": "Ch 7 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz8",
        "hiZWatts": 125
      },
      {
        "id": "loz8",
        "label": "Ch 8 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 60,
        "ratedImpedance": 8,
        "minImpedance": 4
      }
    ]
  },
  {
    "modelId": "ProA250.1",
    "name": "ProA250.1",
    "series": "Pro",
    "subtitle": "2× Lo-Z · 1× Hi-Z",
    "dealer": 742,
    "msrp": 1237,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz2",
        "hiZWatts": 250
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4
      }
    ]
  },
  {
    "modelId": "ProA250.2",
    "name": "ProA250.2",
    "series": "Pro",
    "subtitle": "4× Lo-Z · 2× Hi-Z",
    "dealer": 1065,
    "msrp": 1774,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz2",
        "hiZWatts": 250
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4
      },
      {
        "id": "loz3",
        "label": "Ch 3 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz4",
        "hiZWatts": 250
      },
      {
        "id": "loz4",
        "label": "Ch 4 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4
      }
    ]
  },
  {
    "modelId": "ProA250.4",
    "name": "ProA250.4",
    "series": "Pro",
    "subtitle": "8× Lo-Z · 4× Hi-Z",
    "dealer": 1839,
    "msrp": 3064,
    "channels": [
      {
        "id": "loz1",
        "label": "Ch 1 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz2",
        "hiZWatts": 250
      },
      {
        "id": "loz2",
        "label": "Ch 2 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4
      },
      {
        "id": "loz3",
        "label": "Ch 3 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz4",
        "hiZWatts": 250
      },
      {
        "id": "loz4",
        "label": "Ch 4 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4
      },
      {
        "id": "loz5",
        "label": "Ch 5 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz6",
        "hiZWatts": 250
      },
      {
        "id": "loz6",
        "label": "Ch 6 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4
      },
      {
        "id": "loz7",
        "label": "Ch 7 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4,
        "btlPairId": "loz8",
        "hiZWatts": 250
      },
      {
        "id": "loz8",
        "label": "Ch 8 Lo-Z",
        "outputMode": "lo-z",
        "maxWatts": 125,
        "ratedImpedance": 8,
        "minImpedance": 4
      }
    ]
  }
];

const AMP_ORDER = [
  'ProA125.1','ProA125.2','ProA125.4',
  'ProA250.1','ProA250.2','ProA250.4',
  'ProA1000.1','ProA1000.2','ProA1000.4',
  'ProA1200.1','ProA1200.2','ProA1200.4',
  'DSP2-200','DSP3-150','DSP60.8',
  'SubA150','SubA500',
]
export const AMPS_SORTED = [...AMPS].sort((a, b) => {
  const ai = AMP_ORDER.indexOf(a.modelId)
  const bi = AMP_ORDER.indexOf(b.modelId)
  return (ai < 0 ? 999 : ai) - (bi < 0 ? 999 : bi)
})

export const SPEAKERS: SpeakerModel[] = [
  {
    "modelId": "C63",
    "name": "C63",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 113,
    "msrp": 328
  },
  {
    "modelId": "C65",
    "name": "C65",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 146,
    "msrp": 420
  },
  {
    "modelId": "C65EX",
    "name": "C65EX",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 178,
    "msrp": 511
  },
  {
    "modelId": "C67",
    "name": "C67",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 178,
    "msrp": 511
  },
  {
    "modelId": "C69",
    "name": "C69",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 301,
    "msrp": 855
  },
  {
    "modelId": "CIW61",
    "name": "CIW61",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 183,
    "msrp": 527
  },
  {
    "modelId": "CIW63",
    "name": "CIW63",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 232,
    "msrp": 667
  },
  {
    "modelId": "CIW65",
    "name": "CIW65",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "D101",
    "name": "D101",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 307,
    "msrp": 882
  },
  {
    "modelId": "D103DT",
    "name": "D103DT",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 420,
    "msrp": 1204
  },
  {
    "modelId": "D105",
    "name": "D105",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 490,
    "msrp": 1414
  },
  {
    "modelId": "D105EX",
    "name": "D105EX",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 559,
    "msrp": 1602
  },
  {
    "modelId": "D107",
    "name": "D107",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 629,
    "msrp": 1828
  },
  {
    "modelId": "D109",
    "name": "D109",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 748,
    "msrp": 2150
  },
  {
    "modelId": "D39",
    "name": "D39",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 10,
    "dealer": 178,
    "msrp": 511
  },
  {
    "modelId": "D51DT",
    "name": "D51DT",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 146,
    "msrp": 420
  },
  {
    "modelId": "D53",
    "name": "D53",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 113,
    "msrp": 328
  },
  {
    "modelId": "D53DT",
    "name": "D53DT",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6
  },
  {
    "modelId": "D55",
    "name": "D55",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 146,
    "msrp": 420
  },
  {
    "modelId": "D55EX",
    "name": "D55EX",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 178,
    "msrp": 511
  },
  {
    "modelId": "D57",
    "name": "D57",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 178,
    "msrp": 511
  },
  {
    "modelId": "D57DT/SUR",
    "name": "D57DT/SUR",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 215,
    "msrp": 619
  },
  {
    "modelId": "D59",
    "name": "D59",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 237,
    "msrp": 683
  },
  {
    "modelId": "D61DT",
    "name": "D61DT",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 146,
    "msrp": 420
  },
  {
    "modelId": "D63",
    "name": "D63",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 113,
    "msrp": 328
  },
  {
    "modelId": "D63DT/SUR",
    "name": "D63DT/SUR",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 178,
    "msrp": 511
  },
  {
    "modelId": "D65",
    "name": "D65",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 146,
    "msrp": 420
  },
  {
    "modelId": "D65EX",
    "name": "D65EX",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 178,
    "msrp": 511
  },
  {
    "modelId": "D67",
    "name": "D67",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 178,
    "msrp": 511
  },
  {
    "modelId": "D69",
    "name": "D69",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 301,
    "msrp": 855
  },
  {
    "modelId": "D80DT",
    "name": "D80DT",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 167,
    "msrp": 479
  },
  {
    "modelId": "D83",
    "name": "D83",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 167,
    "msrp": 484
  },
  {
    "modelId": "D83A",
    "name": "D83A",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 183,
    "msrp": 533
  },
  {
    "modelId": "D83AEX",
    "name": "D83AEX",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 221,
    "msrp": 635
  },
  {
    "modelId": "D83DT/SUR",
    "name": "D83DT/SUR",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 264,
    "msrp": 753
  },
  {
    "modelId": "D83DT/SUR EX",
    "name": "D83DT/SUR EX",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 328,
    "msrp": 941
  },
  {
    "modelId": "D83EX",
    "name": "D83EX",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 210,
    "msrp": 602
  },
  {
    "modelId": "D85",
    "name": "D85",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 237,
    "msrp": 683
  },
  {
    "modelId": "D85EX",
    "name": "D85EX",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 285,
    "msrp": 817
  },
  {
    "modelId": "D87",
    "name": "D87",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 339,
    "msrp": 973
  },
  {
    "modelId": "D89",
    "name": "D89",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 576,
    "msrp": 1694
  },
  {
    "modelId": "LCR37",
    "name": "LCR37",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 129,
    "msrp": 377
  },
  {
    "modelId": "LCR39",
    "name": "LCR39",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 194,
    "msrp": 565
  },
  {
    "modelId": "LCR65",
    "name": "LCR65",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 194,
    "msrp": 565
  },
  {
    "modelId": "LCR67",
    "name": "LCR67",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 269,
    "msrp": 774
  },
  {
    "modelId": "LCR69",
    "name": "LCR69",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 377,
    "msrp": 1086
  },
  {
    "modelId": "M2500",
    "name": "M2500",
    "collection": "Marquee",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "M3500",
    "name": "M3500",
    "collection": "Marquee",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "M5500",
    "name": "M5500",
    "collection": "Marquee",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "OSR65",
    "name": "OSR65",
    "collection": "Seasons",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "OSR85",
    "name": "OSR85",
    "collection": "Seasons",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "OS50B",
    "name": "OS50B",
    "collection": "Seasons",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 242,
    "msrp": 538
  },
  {
    "modelId": "OS60B",
    "name": "OS60B",
    "collection": "Seasons",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 301,
    "msrp": 667
  },
  {
    "modelId": "OS60DTB",
    "name": "OS60DTB",
    "collection": "Seasons",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 205,
    "msrp": 457
  },
  {
    "modelId": "OS80B",
    "name": "OS80B",
    "collection": "Seasons",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 457,
    "msrp": 1011
  },
  {
    "modelId": "TF37DTEX",
    "name": "TF37DTEX",
    "collection": "ThinFit",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 199,
    "msrp": 570
  },
  {
    "modelId": "TF37EX",
    "name": "TF37EX",
    "collection": "ThinFit",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 172,
    "msrp": 495
  },
  {
    "modelId": "TFIW37EX",
    "name": "TFIW37EX",
    "collection": "ThinFit",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 199,
    "msrp": 570
  },
  {
    "modelId": "THTR67",
    "name": "THTR67",
    "collection": "Theater",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "THTR69",
    "name": "THTR69",
    "collection": "Theater",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "dealer": 807,
    "msrp": 2322
  },
  {
    "modelId": "Blends602",
    "name": "Blends602",
    "collection": "BLENDS",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "sensitivity": 83,
    "maxWatts": 50,
    "dealer": 650,
    "msrp": 1625
  },
  {
    "modelId": "Blends802",
    "name": "Blends802",
    "collection": "BLENDS",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "sensitivity": 83,
    "maxWatts": 60,
    "dealer": 860,
    "msrp": 2150
  },
  {
    "modelId": "Blends803",
    "name": "Blends803",
    "collection": "BLENDS",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "sensitivity": 83,
    "maxWatts": 80,
    "dealer": 1075,
    "msrp": 2625
  },
  {
    "modelId": "P80DT",
    "name": "P80DT",
    "collection": "Producer",
    "brand": "Origin Pro",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "PC50",
    "name": "PC50",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 6,
    "tapOptions": [
      30,
      15,
      7.5,
      3.8
    ],
    "sensitivity": 89,
    "maxWatts": 30,
    "coverageAngle": 120,
    "dealer": 242,
    "msrp": 484
  },
  {
    "modelId": "PC60",
    "name": "PC60",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 6,
    "tapOptions": [
      60,
      30,
      15,
      7.5
    ],
    "sensitivity": 91,
    "maxWatts": 40,
    "coverageAngle": 115,
    "dealer": 301,
    "msrp": 602
  },
  {
    "modelId": "PC60S",
    "name": "PC60S",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 6,
    "tapOptions": [
      60,
      30,
      15,
      7.5
    ],
    "sensitivity": 87,
    "maxWatts": 40,
    "coverageAngle": 90,
    "dealer": 301,
    "msrp": 602
  },
  {
    "modelId": "PC80",
    "name": "PC80",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 6,
    "tapOptions": [
      60,
      30,
      15,
      7.5
    ],
    "sensitivity": 92,
    "maxWatts": 60,
    "coverageAngle": 100,
    "dealer": 447,
    "msrp": 893
  },
  {
    "modelId": "PP50",
    "name": "PP50",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [30, 15, 7.5, 3.75],
    "sensitivity": 87,
    "maxWatts": 50,
    "coverageAngle": 120,
    "dealer": 301,
    "msrp": 602
  },
  {
    "modelId": "PP60",
    "name": "PP60",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [60, 30, 15, 7.5],
    "sensitivity": 88,
    "maxWatts": 65,
    "coverageAngle": 120,
    "dealer": 366,
    "msrp": 731
  },
  {
    "modelId": "PP80",
    "name": "PP80",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [60, 30, 15, 7.5],
    "sensitivity": 90,
    "maxWatts": 100,
    "coverageAngle": 110,
    "dealer": 538,
    "msrp": 1075
  },
  {
    "modelId": "PS50",
    "name": "PS50",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [
      30,
      15,
      7.5,
      3.75
    ],
    "sensitivity": 89,
    "maxWatts": 30,
    "coverageAngle": 100,
    "dealer": 291,
    "msrp": 581
  },
  {
    "modelId": "PS60",
    "name": "PS60",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [
      60,
      30,
      15,
      7.5
    ],
    "sensitivity": 92,
    "maxWatts": 40,
    "coverageAngle": 100,
    "dealer": 355,
    "msrp": 710
  },
  {
    "modelId": "PS80",
    "name": "PS80",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [
      80,
      40,
      20,
      10
    ],
    "sensitivity": 92,
    "maxWatts": 60,
    "coverageAngle": 70,
    "dealer": 527,
    "msrp": 1054
  },
  {
    "modelId": "6.5HD2-4ohm",
    "name": "6.5HD2-4ohm",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 4,
    "sensitivity": 95,
    "maxWatts": 200,
    "coverageAngle": 110,
    "dealer": 1935,
    "msrp": 3870
  },
  {
    "modelId": "6.5HD2-70V",
    "name": "6.5HD2-70V",
    "collection": "HD",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "specsUnavailable": true,
    "sensitivity": 95,
    "maxWatts": 200,
    "coverageAngle": 110
  },
  {
    "modelId": "6.5HD-70V",
    "name": "6.5HD-70V",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [70, 100],
    "sensitivity": 89,
    "maxWatts": 100,
    "coverageAngle": 110,
    "dealer": 1075,
    "msrp": 2150
  },
  {
    "modelId": "6.5HD-8ohm",
    "name": "6.5HD-8ohm",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 8,
    "sensitivity": 89,
    "maxWatts": 100,
    "coverageAngle": 110,
    "dealer": 968,
    "msrp": 1935
  },
  {
    "modelId": "ALSB106",
    "name": "ALSB106",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "tappable",
    "impedance": 6,
    "tapOptions": [200, 100, 70],
    "dealer": 1613,
    "msrp": 3360
  },
  {
    "modelId": "ALSB64",
    "name": "ALSB64",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "tappable",
    "impedance": 6,
    "tapOptions": [100, 70, 50],
    "dealer": 807,
    "msrp": 1882
  },
  {
    "modelId": "ALSB85",
    "name": "ALSB85",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "tappable",
    "impedance": 6,
    "tapOptions": [100, 70, 50],
    "dealer": 1210,
    "msrp": 2634
  },
  {
    "modelId": "LSR40",
    "name": "LSR40",
    "collection": "Seasons",
    "brand": "Ambisonic",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [
      70,
      50
    ],
    "sensitivity": 85,
    "maxWatts": 50,
    "dealer": 323,
    "msrp": 645
  },
  {
    "modelId": "LSR60",
    "name": "LSR60",
    "collection": "Seasons",
    "brand": "Ambisonic",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [
      70,
      75
    ],
    "sensitivity": 88,
    "maxWatts": 75,
    "dealer": 484,
    "msrp": 968
  },
  {
    "modelId": "LSR80",
    "name": "LSR80",
    "collection": "Seasons",
    "brand": "Ambisonic",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [
      70,
      100
    ],
    "sensitivity": 89,
    "maxWatts": 100,
    "dealer": 592,
    "msrp": 1183
  },
  {
    "modelId": "AM5600",
    "name": "AM5600",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 4,
    "dealer": 2903,
    "msrp": 7875
  },
  {
    "modelId": "AM3600",
    "name": "AM3600",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 4,
    "dealer": 1935,
    "msrp": 5250
  },
  {
    "modelId": "AM6500A",
    "name": "AM6500A",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 4,
    "dealer": 914,
    "msrp": 2465
  },
  {
    "modelId": "ASM63",
    "name": "ASM63",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 1000,
    "msrp": 2000
  },
  {
    "modelId": "MOS36K",
    "name": "MOS36K",
    "collection": "MOS",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 4,
    "sensitivity": 84,
    "maxWatts": 75,
    "dealer": 592,
    "msrp": 1495
  },
  {
    "modelId": "LSH80",
    "name": "LSH80",
    "collection": "AMBI",
    "brand": "Origin Acoustics",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [
      70,
      100
    ],
    "sensitivity": 89,
    "maxWatts": 100,
    "coverageAngle": 100,
    "dealer": 550,
    "msrp": 1100
  },
  {
    "modelId": "LSH60",
    "name": "LSH60",
    "collection": "AMBI",
    "brand": "Origin Acoustics",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [
      70,
      75
    ],
    "sensitivity": 88,
    "maxWatts": 75,
    "coverageAngle": 110,
    "dealer": 450,
    "msrp": 900
  },
  {
    "modelId": "LSH40",
    "name": "LSH40",
    "collection": "AMBI",
    "brand": "Origin Acoustics",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [
      70,
      50
    ],
    "sensitivity": 85,
    "maxWatts": 50,
    "coverageAngle": 120,
    "dealer": 300,
    "msrp": 600
  }
];

export const SUBS: SpeakerModel[] = [
  {
    "modelId": "ASM63SUB",
    "name": "ASM63SUB",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 8,
    "sensitivity": 89,
    "maxWatts": 150,
    "dealer": 650,
    "msrp": 1290
  },
  {
    "modelId": "10BP-IG-70V",
    "name": "10BP-IG-70V",
    "collection": "Seasons",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "specsUnavailable": true,
    "sensitivity": 91,
    "maxWatts": 300
  },
  {
    "modelId": "10BP-IG-8ohm",
    "name": "10BP-IG-8ohm",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 8,
    "sensitivity": 91,
    "maxWatts": 300,
    "dealer": 1828,
    "msrp": 3655
  },
  {
    "modelId": "10HDR-AW-70V",
    "name": "10HDR-AW-70V",
    "collection": "Seasons",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "specsUnavailable": true,
    "sensitivity": 97,
    "maxWatts": 300
  },
  {
    "modelId": "10HDR-AW-8ohm",
    "name": "10HDR-AW-8ohm",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 8,
    "sensitivity": 97,
    "maxWatts": 300,
    "dealer": 1237,
    "msrp": 2473
  },
  {
    "modelId": "12BP-IG-70v KIT",
    "name": "12BP-IG-70v KIT",
    "collection": "Seasons",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "12BP-IG-8ohm",
    "name": "12BP-IG-8ohm",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 2258,
    "msrp": 4515
  },
  {
    "modelId": "12HDR-AW-70V",
    "name": "12HDR-AW-70V",
    "collection": "Seasons",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "specsUnavailable": true,
    "sensitivity": 91,
    "maxWatts": 1200
  },
  {
    "modelId": "12HDR-AW-8ohm",
    "name": "12HDR-AW-8ohm",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 8,
    "sensitivity": 91,
    "maxWatts": 1200,
    "dealer": 2150,
    "msrp": 4300
  },
  {
    "modelId": "AMD10-SUB",
    "name": "AMD10-SUB",
    "collection": "AMBI",
    "brand": "Ambisonic",
    "speakerType": "lo-z",
    "impedance": 4,
    "dealer": 1344,
    "msrp": 3875
  },
  {
    "modelId": "Blends800Sub",
    "name": "Blends800Sub",
    "collection": "BLENDS",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "BlendsCSUB10",
    "name": "BlendsCSUB10",
    "collection": "BLENDS",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "CSUB10R EX",
    "name": "CSUB10R EX",
    "collection": "Composer",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 8,
    "dealer": 968,
    "msrp": 1935
  },
  {
    "modelId": "DBA10EX",
    "name": "DBA10EX",
    "collection": "Director",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 4,
    "dealer": 285,
    "msrp": 656
  },
  {
    "modelId": "DSUB6X2",
    "name": "DSUB6X2",
    "collection": "Deep",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "impedance": 6,
    "sensitivity": 90,
    "maxWatts": 120
  },
  {
    "modelId": "OSUB10",
    "name": "OSUB10",
    "collection": "Seasons",
    "brand": "Origin Acoustics",
    "speakerType": "hi-z",
    "tapOptions": [
      300
    ],
    "dealer": 1011,
    "msrp": 2021
  },
  {
    "modelId": "OSUB12",
    "name": "OSUB12",
    "collection": "Seasons",
    "brand": "Origin Acoustics",
    "speakerType": "hi-z",
    "tapOptions": [
      300
    ],
    "dealer": 1376,
    "msrp": 2747
  },
  {
    "modelId": "PCSUB8",
    "name": "PCSUB8",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [120, 60, 30, 15],
    "sensitivity": 90,
    "maxWatts": 125,
    "dealer": 307,
    "msrp": 613
  },
  {
    "modelId": "PPSUB8",
    "name": "PPSUB8",
    "collection": "Pro",
    "brand": "Origin Pro",
    "speakerType": "tappable",
    "impedance": 8,
    "tapOptions": [120, 60, 30, 15],
    "sensitivity": 90,
    "maxWatts": 125,
    "dealer": 323,
    "msrp": 570
  },
  {
    "modelId": "PSUB10X2",
    "name": "PSUB10X2",
    "collection": "Pro",
    "brand": "Origin Acoustics",
    "speakerType": "tappable",
    "impedance": 4,
    "tapOptions": [300, 150, 75],
    "sensitivity": 94,
    "maxWatts": 600,
    "coverageAngle": 360,
    "dealer": 780,
    "msrp": 1290
  },
  {
    "modelId": "SUBD10",
    "name": "SUBD10",
    "collection": "Deep",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "SUBD8",
    "name": "SUBD8",
    "collection": "Deep",
    "brand": "Origin Acoustics",
    "speakerType": "lo-z",
    "specsUnavailable": true
  },
  {
    "modelId": "SUBS10",
    "name": "SUBS10",
    "collection": "Slim",
    "brand": "Origin Acoustics",
    "speakerType": "tappable",
    "impedance": 4,
    "tapOptions": [
      300,
      150,
      75
    ],
    "sensitivity": 94,
    "maxWatts": 300,
    "dealer": 807,
    "msrp": 1774
  }
];

export const MUSIC_SOURCE: SourceModel = {
  modelId: 'music-source',
  name: 'Music Source',
  badge: 'STREAM',
  description: 'Generic streaming source (WiiM, Bluesound, etc.)',
};
